PrayerTimes.Web/Pages/Documentation.cshtml.cs
using System.Text;
using Markdig;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PrayerTimes.Web.Pages
{
    public class DocumentationModel : PageModel
    {
        private readonly ILogger<DocumentationModel> _logger;

       
        public string Documentation { get; set; } = string.Empty;

        public DocumentationModel(ILogger<DocumentationModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            string documentation;
            using (var streamReader = new StreamReader(@"Documentation/Documentation.html", Encoding.UTF8))
            {
                documentation = streamReader.ReadToEnd();
            }

            
            Documentation = documentation;
        }
    }
}

PrayerTimes.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace PrayerTimes.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PrayerTimes.Web/Pages/Index.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Text;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using NodaTime;
using PrayerTimes.Library.Calculators;
using PrayerTimes.Library.Enumerations;
using PrayerTimes.Library.Helpers;
using PrayerTimes.Library.Models;
using PrayerTimes.Web.Helpers;
using PrayerTimes.Web.Models;
using TimeZoneNames;

namespace PrayerTimes.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public PrayerTimeCalculatorModel PrayerTimeCalculatorModel { get; set; }

        private static List<InternalTimeZoneInfo> TimeZoneList { get; set; } = new List<InternalTimeZoneInfo>();

        public string PrayerTimes { get; set; }

        public PrayerTimesOutputModel PrayerTimesOutput { get; set; }
        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }


        public void OnPostSubmit(PrayerTimeCalculatorModel prayerTimeCalculatorModel)
        {
            if (prayerTimeCalculatorModel.DayLightSavingsTime)
            {
                prayerTimeCalculatorModel.TimeZone += 1.0;
            }

            if (prayerTimeCalculatorModel.CalculationMethodPreset == CalculationMethodPreset.Custom)
            {
                prayerTimeCalculatorModel.CalculationMethodPreset = CalculationMethodPreset.IthnaAshari;
            }

            var when = Instant.FromDateTimeUtc(prayerTimeCalculatorModel.CalculationDate.ToUniversalTime());
            var settings = new PrayerCalculationSettings();
            settings.CalculationMethod.SetCalculationMethodPreset(when, prayerTimeCalculatorModel.CalculationMethodPreset);
            var geo = new Geocoordinate(prayerTimeCalculatorModel.Latitude, prayerTimeCalculatorModel.Longitude, prayerTimeCalculatorModel.Altitude);

            var prayer = Prayers.On(when, settings, geo, prayerTimeCalculatorModel.TimeZone);
            var solarDate = prayertimescore.PrayerTimes.Library.Calender.Calendar.ConvertToPersian(prayerTimeCalculatorModel.CalculationDate);
            var lunarDate = prayertimescore.PrayerTimes.Library.Calender.Calendar.ConvertToIslamic(prayerTimeCalculatorModel.CalculationDate.AddDays(prayerTimeCalculatorModel.LunarHijriOffset));
            var gregorianDate = prayerTimeCalculatorModel.CalculationDate;

            var solarDateString = $" {solarDate.ToString("english_day")} {solarDate.ToString("english_month")} {solarDate.ToString("english_year")}";

            var sb = new StringBuilder();
            sb.AppendLine(
                "<div class=\"alert alert-success\" role=\"alert\">");
            sb.AppendLine("<table class=\"table table-dark table-hover table-bordered mb-12\"><tbody>");

            sb.AppendLine("<table class=\"table table-dark table-hover table-bordered mb-12\"><tbody>");
            sb.AppendLine("<tr><th>Method and Parameters</th></tr><tr>");
            sb.AppendLine("<td><table class\"table table-light table-bordered\"><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Calculation Method</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GetDescription(prayerTimeCalculatorModel.CalculationMethodPreset)}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Calculation Date</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{prayerTimeCalculatorModel.CalculationDate:D}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Lunar Hijri Offset</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GenerateLunarHijriOffsetString(prayerTimeCalculatorModel.LunarHijriOffset)}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Timezone</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GetTimeZoneFromOffset(prayerTimeCalculatorModel.TimeZone, prayerTimeCalculatorModel.DayLightSavingsTime)} (DST: {GetDstStatus(prayerTimeCalculatorModel.DayLightSavingsTime)})</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Geo Coordinates</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GetCoordinates(prayerTimeCalculatorModel.Latitude, prayerTimeCalculatorModel.Longitude, prayerTimeCalculatorModel.Altitude)}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Geo Raw</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GetGeoRaw(prayerTimeCalculatorModel.Latitude, prayerTimeCalculatorModel.Longitude, prayerTimeCalculatorModel.Altitude)}</td>");
            sb.AppendLine("</tr></table></td><tr>");

            sb.AppendLine("<table class=\"table table-dark table-hover table-bordered mb-12\"><tbody>");
            sb.AppendLine("<tr><th>Dates</th></tr><tr>");
            sb.AppendLine("<td><table class\"table table-light table-bordered\"><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Gregorian</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{gregorianDate:D}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Solar Hijri</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{solarDateString}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Lunar Hijri</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{lunarDate.ToString("english_formatted")}</td>");
            sb.AppendLine("</tr></table></td><tr>");

            sb.AppendLine("<tr><th>Prayer Times</th></tr><tr>");
            sb.AppendLine("<td><table class\"table table-light table-bordered\"><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Imsaak</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GetPrayerTimeString(prayer.Imsak, prayerTimeCalculatorModel.TimeZone)}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Fajr</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GetPrayerTimeString(prayer.Fajr, prayerTimeCalculatorModel.TimeZone)}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Sunrise</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GetPrayerTimeString(prayer.Sunrise, prayerTimeCalculatorModel.TimeZone)}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Dhuhr</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GetPrayerTimeString(prayer.Dhuhr, prayerTimeCalculatorModel.TimeZone)}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Asr</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GetPrayerTimeString(prayer.Asr, prayerTimeCalculatorModel.TimeZone)}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Sunset</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GetPrayerTimeString(prayer.Sunset, prayerTimeCalculatorModel.TimeZone)}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Maghrib</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GetPrayerTimeString(prayer.Maghrib, prayerTimeCalculatorModel.TimeZone)}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Isha</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GetPrayerTimeString(prayer.Isha, prayerTimeCalculatorModel.TimeZone)}</td>");
            sb.AppendLine("</tr><tr>");
            sb.AppendLine($"<td scope=\"row\" class=\"col-1\">&nbsp;</td><td scope=\"row\" class=\"col-4\"><b>Midnight</b></td><td scope=\"row\" class=\"col-1\">&nbsp;</td><td class=\"col-6\" >{GetPrayerTimeString(prayer.Midnight, prayerTimeCalculatorModel.TimeZone)}</td>");
            sb.AppendLine("</tr></table></td><tr>");
            sb.AppendLine("</tbody></tr>");
            sb.AppendLine("</table>");
            sb.AppendLine("</div>");
            sb.AppendLine("<hr/>");

            PrayerTimes = sb.ToString();
        }

        private string GetGeoRaw(double latitude, double longitude, double altitude) => 
            altitude > 0 ? 
                $"Latitude: {latitude:F5}, Longitude: {longitude:F5}, Altitude: {altitude:F5} meters" :
                $"Latitude: {latitude:F5}, Longitude: {longitude:F5}";

        private string GenerateLunarHijriOffsetString(int lunarHijriOffset)
        {
            var offsetString = $"{lunarHijriOffset}";
            if (offsetString.Contains("-"))
            {

PrayerTimes.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PrayerTimes.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

PrayerTimes.Web/Pages/Documentation.cshtml
@page
@model PrayerTimes.Web.Pages.DocumentationModel
@{
    ViewData["Title"] = "Documentation";
}

<div class="align-content-lg-end">
    @Html.Raw(Model.Documentation)
</div>

PrayerTimes.Web/Pages/Index.cshtml
@page
@model IndexModel

@{
    ViewData["Title"] = "Home";
}

<div class="align-content-lg-end">
    @Html.Raw(Model.PrayerTimes)
</div>

<div class="container">

    <form method="post" class="row g-3" novalidate>
        <div class="col-md-4">
            <label for="latitude" class="form-label">Latitude</label>
            <input class="form-control"
                   asp-for="PrayerTimeCalculatorModel.Latitude"
                   type="text"
                   id="latitude"
                   required />
        </div>
        <div class="col-md-4">
            <label for="longitude" class="form-label">Longitude</label>
            <input class="form-control"
                   asp-for="PrayerTimeCalculatorModel.Longitude"
                   type="text"
                   id="longitude"
                   required />
        </div>
        <div class="col-md-4">
            <label for="altitude" class="form-label">Altitude</label>
            <input class="form-control"
                   asp-for="PrayerTimeCalculatorModel.Altitude"
                   type="text"
                   id="altitude"
                   required />
        </div>
        <div class="col-md-4">
            <label for="calculation-date" class="form-label">Calculation Date</label>
            <input class="form-control"
                   asp-for="PrayerTimeCalculatorModel.CalculationDate"
                   type="date"
                   value="@DateTime.Now.ToString("yyyy-MM-dd")"
                   id="calculation-date"
                   required />
        </div>
        <div class="col-md-4">
            <label for="lunar-hijri-date-offset" class="form-label">Lunar Hijri Date Offset (<span id="offset-value">0</span>)</label>
            <input class="form-range"
                   type="range"
                   asp-for="PrayerTimeCalculatorModel.LunarHijriOffset"
                   min="-3"
                   max="3"
                   id="lunar-hijri-date-offset"
                   required
                   onChange="document.getElementById('offset-value').innerText = document.getElementById('lunar-hijri-date-offset').value" />
        </div>
        <div class="col-md-4">
            <label for="timezone-drop-down" class="form-label">Calculation Method</label>
            <select asp-for="PrayerTimeCalculatorModel.CalculationMethodPreset"
                    asp-items="IndexModel.GetCalculationModePresets()"
                    class="form-select">
                <option selected="selected" value="">Please select a calculation method</option>
            </select>
        </div>
        <div class="col-md-6">
            <label for="timezone-drop-down" class="form-label">Time Zone@* (Detected: <span id="detected-timezone"></span>)*@</label>
            <select asp-for="PrayerTimeCalculatorModel.TimeZone"
                    asp-items="IndexModel.GetCountriesList()"
                    class="form-select"
                    id="timezone-drop-down">
                <option selected="selected" value="">Please select your timezone</option>
            </select>
        </div>
        <div class="col-md-6">
            <label for="dst-dropdown" class="form-label">Daylight Savings Time</label>
            <select asp-for="PrayerTimeCalculatorModel.DayLightSavingsTime"
                    class="form-select"
                    id="dst-dropdown">
                <option selected="selected" value="false">Daylight Savings Time is OFF</option>
                <option value="true">Daylight Savings Time is ON</option>
            </select>
        </div>
        <div class="d-grid gap-2">
            <input class="btn btn-dark"
                   type="submit"
                   value="Calculate"
                   asp-page-handler="Submit" />
        </div>
        <hr />
    </form>
</div>

<div class="alert-danger">
    <p id="location-info">

    </p>
</div>

<script>
    window.onload = getLocation();
    //window.onload = addLocalTimezone();
    

    var x = document.getElementById("location-info");
    var latForm = document.getElementById("latitude");
    var longForm = document.getElementById("longitude");
    var altForm = document.getElementById("altitude");
    var timezoneSpan = document.getElementById("detected-timezone");
    //timezoneSpan.innerHTML = Intl.DateTimeFormat().resolvedOptions().timeZone;

    //function addLocalTimezone()
    //{
    //    //fetch("http://api.namaaz.net/api/timezoneConverter")
    //    //    .then( res => res.json())
    //    //    .then(response => {
    //    //        processUserData(response)
    //    //    })
    //    //    .catch(status => {
    //    //        ipLookup()
    //    //    })


    //    // Create an Option object       
    //    var opt = document.createElement("option");        

    //    // Assign text and value to Option object
    //    opt.text = Intl.DateTimeFormat().resolvedOptions().timeZone;
    //    opt.value = "Something";
    //    opt.selected = true;

    //    // Add an Option object to Drop Down List Box
    //    document.getElementById('timezone-drop-down').options.add(opt);
    //}

    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
        } else {
            x.innerHTML = "Geolocation is not supported by this browser.";
        }
    }

    function showPosition(position) {

        latForm.value = position.coords.latitude;
        longForm.value = position.coords.longitude;
        if (position.coords.altitude === null) {
            altForm.value = 0.0;
        } else {
            altForm.value = position.coords.altitude;
        }
    }
</script>